name: flutter_carrotquest
description: A Carrot quest flutter plugin for Android and IOS. You can find a description of the service at https://www.carrotquest.io
version: 1.0.0-dev.4
repository: https://gitlab.com/dipdev.studio/open-source/flutter/flutter_carrotquest
homepage: https://www.carrotquest.io

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.carrotquest.flutter_carrotquest
        pluginClass: FlutterCarrotquestPlugin
      ios:
        pluginClass: FlutterCarrotquestPlugin